package io.fairyproject.event;

import io.fairyproject.util.Either;

public interface Cancellable {

    default boolean isCancelled() {
        throw new UnsupportedOperationException("Not implemented (has it generated by gradle plugin?)");
    }

    default void setCancelled(boolean cancelled) {
        throw new UnsupportedOperationException("Not implemented (has it generated by gradle plugin?)");
    }

    default Either<?, ?> either() {
        if (this.isCancelled()) {
            return Either.left(null);
        } else {
            return Either.right(null);
        }
    }

}
