package io.fairyproject.gradle.resource.impl

import io.fairyproject.gradle.extension.FairyExtension
import io.fairyproject.gradle.resource.*
import org.gradle.api.Project
import org.gradle.api.artifacts.Dependency
import java.util.*


/**
 * The resource generator for bukkit plugin.yml
 */
class FairyResourceBukkitMeta : FairyResource {
    override fun generate(
        project: Project,
        fairyExtension: FairyExtension,
        classMapper: Map<ClassType, ClassInfo>
    ): ResourceInfo? {
        val hasBukkit = project.configurations.flatMap { it.dependencies }.any {
            it.hasBukkitPlatform
        }
        if (!hasBukkit)
            return null

        classMapper[ClassType.BUKKIT_PLUGIN] ?: return null
        val stringJoiner = StringJoiner("\n")

        stringJoiner.add("# Generated by Fairy")
        stringJoiner.add("name: ${fairyExtension.name.getOrElse(project.name)}")
        stringJoiner.add("version: ${project.version}")
        stringJoiner.add("description: ${project.description}");
        stringJoiner.add("main: ${classMapper[ClassType.BUKKIT_PLUGIN]!!.name.replace('/', '.')}")
        fairyExtension.bukkitProperties().forEach { key, value ->
            if (value is List<*>) {
                stringJoiner.add("$key:")
                value.forEach {
                    if (it is String) {
                        stringJoiner.add("- \'$it\'")
                    } else {
                        stringJoiner.add("- $it")
                    }
                }
            } else
                stringJoiner.add("$key: $value")
        }

        return resourceOf("plugin.yml", stringJoiner.toString().encodeToByteArray())
    }

    private val Dependency.hasBukkitPlatform
    get() = group == "io.fairyproject" &&
                (name == "bukkit-platform" || name == "bukkit-bundles" || name == "bukkit-bootstrap")
}