package io.fairyproject.gradle.resource.impl

import io.fairyproject.gradle.extension.property.Properties
import io.fairyproject.gradle.resource.*
import java.util.*


/**
 * The resource generator for bukkit plugin.yml
 */
class FairyResourceBukkitMeta : FairyResource {
    override fun generate(
        context: FairyResourceGenerateContext,
        classMapper: Map<ClassType, ClassInfo>
    ): ResourceInfo? {
        if (!context.hasBukkitPlatform)
            return null

        classMapper[ClassType.BUKKIT_PLUGIN] ?: return null
        val stringJoiner = StringJoiner("\n")

        stringJoiner.add("# Generated by Fairy")
        stringJoiner.add("name: ${context.pluginName}")
        stringJoiner.add("version: ${context.projectVersion}")
        stringJoiner.add("description: ${context.projectDescription}");
        stringJoiner.add("main: ${classMapper[ClassType.BUKKIT_PLUGIN]!!.name.replace('/', '.')}")
        context.props.forEach { key, value ->
            if (value is List<*>) {
                stringJoiner.add("$key:")
                value.forEach {
                    if (it is String) {
                        stringJoiner.add("- \'$it\'")
                    } else {
                        stringJoiner.add("- $it")
                    }
                }
            } else
                stringJoiner.add("$key: $value")
        }

        return resourceOf("plugin.yml", stringJoiner.toString().encodeToByteArray())
    }

}