package io.fairyproject.gradle.file;

import io.fairyproject.gradle.util.PropertyUtil;
import org.apache.commons.lang3.tuple.Pair;
import io.fairyproject.gradle.FairyExtension;
import io.fairyproject.gradle.PlatformType;

import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;

public class FileGeneratorBukkit implements FileGenerator {

    private static final String BOOTSTRAP_CLASS = ".bootstrap.bukkit.BukkitPlugin";

    @Override
    public Pair<String, byte[]> generate(FairyExtension extension, String mainClass) {
        StringJoiner stringJoiner = new StringJoiner("\n");

        stringJoiner.add("# Generated by Fairy");
        stringJoiner.add("name: " + extension.getName().get());
        stringJoiner.add("version: " + extension.getVersion().get());
        stringJoiner.add("main: " + extension.getShadedPackage().get() + BOOTSTRAP_CLASS);
        PropertyUtil.ifPresent(extension.getDescription(), description -> stringJoiner.add("description: " + description));
        extension.properties(PlatformType.BUKKIT).forEach((k, v) -> stringJoiner.add(k + ": " + v));

        return Pair.of("plugin.yml", stringJoiner.toString().getBytes(StandardCharsets.UTF_8));
    }
}
