package io.fairyproject.gradle.file;

import io.fairyproject.gradle.FairyBuildData;
import io.fairyproject.gradle.PlatformType;
import org.apache.commons.lang3.tuple.Pair;
import org.gradle.api.Project;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.StringJoiner;

public class FileGeneratorBukkit implements FileGenerator {

    private static final String BOOTSTRAP_CLASS = ".fairy.bootstrap.bukkit.BukkitPlugin";

    @Override
    public Pair<String, byte[]> generate(Project project, FairyBuildData extension, String mainClass, List<String> otherModules) {
        if (mainClass == null) {
            return null;
        }
        StringJoiner stringJoiner = new StringJoiner("\n");

        stringJoiner.add("# Generated by Fairy");
        stringJoiner.add("name: " + extension.getName());
        stringJoiner.add("version: " + project.getVersion());
        stringJoiner.add("main: " + extension.getMainPackage() + BOOTSTRAP_CLASS);
        stringJoiner.add("softdepend: [Fairy]");
        if (extension.getDescription() != null) {
            stringJoiner.add(extension.getDescription());
        }
        extension.properties(PlatformType.BUKKIT).forEach((k, v) -> stringJoiner.add(k + ": " + v));

        return Pair.of("plugin.yml", stringJoiner.toString().getBytes(StandardCharsets.UTF_8));
    }
}
